name: Repo Status

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  status:
    name: status
    runs-on: ubuntu-latest
    steps:
      - name: Dashboard
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          {
            echo "## Repo Status"
            echo ""
            echo "- Repo: $GITHUB_REPOSITORY"
            echo "- Ref:  $GITHUB_REF_NAME"
            echo "- SHA:  $GITHUB_SHA"
            echo ""
            echo "### Recent runs (last 15)"
            echo '```'
            gh run list --repo "$GITHUB_REPOSITORY" --limit 15 || true
            echo '```'
            echo ""
            echo "### Open PRs (top 15)"
            echo '```'
            gh pr list --repo "$GITHUB_REPOSITORY" --state open --limit 15 || true
            echo '```'
            echo ""
            echo "### Branch protection (main) (best-effort)"
            echo '```'
            gh api "repos/$GITHUB_REPOSITORY/branches/main/protection" --jq '{protected:true, required_status_checks:(.required_status_checks.contexts // [])}' 2>/dev/null || echo "unavailable"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"