name: Repo Status

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write status summary
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail

          echo "# Repo Status" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "- Repo: $GITHUB_REPOSITORY" >> "$GITHUB_STEP_SUMMARY"
          echo "- Ref: $GITHUB_REF_NAME" >> "$GITHUB_STEP_SUMMARY"
          echo "- SHA: $GITHUB_SHA" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          echo "## Required checks (merge)" >> "$GITHUB_STEP_SUMMARY"
          echo "- scan" >> "$GITHUB_STEP_SUMMARY"
          echo "- audit" >> "$GITHUB_STEP_SUMMARY"
          echo "- boundary" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          echo "## Branch protection (main)" >> "$GITHUB_STEP_SUMMARY"
          if gh api "repos/$GITHUB_REPOSITORY/branches/main/protection" >/tmp/bp.json 2>/dev/null; then
            python - <<'PY' >> "$GITHUB_STEP_SUMMARY"
import json
bp=json.load(open("/tmp/bp.json"))
rsc=bp.get("required_status_checks") or {}
strict=rsc.get("strict")
ctx=rsc.get("contexts") or []
print(f"- protection: enabled")
print(f"- strict: {strict}")
print(f"- contexts: {', '.join(ctx) if ctx else '(none listed)'}")
PY
          else
            echo "- protection: (no access via token)" >> "$GITHUB_STEP_SUMMARY"
          fi
          echo "" >> "$GITHUB_STEP_SUMMARY"

          echo "## Recent runs (top 10)" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| Workflow | Event | Branch | Conclusion | Run |" >> "$GITHUB_STEP_SUMMARY"
          echo "|---|---|---|---|---|" >> "$GITHUB_STEP_SUMMARY"

          gh api "repos/$GITHUB_REPOSITORY/actions/runs?per_page=10" --jq '.workflow_runs[] | [.name, .event, .head_branch, (.conclusion // ""), .html_url] | @tsv' \
            | while IFS=$'\t' read -r name event branch concl url; do
                [ -z "$name" ] && continue
                echo "| $name | $event | $branch | $concl | [link]($url) |" >> "$GITHUB_STEP_SUMMARY"
              done