name: Repo Status

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - name: Summary (human-readable)
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner, repo, per_page: 15, branch: "main"
            });

            const lines = [];
            lines.push(`# Repo Status`);
            lines.push(``);
            lines.push(`## Recent runs (main)`);
            lines.push(`| Status | Workflow | Event | Updated | URL |`);
            lines.push(`|---|---|---|---|---|`);

            for (const r of runs.data.workflow_runs) {
              const status = (r.conclusion || r.status || "").toString();
              const wf     = (r.name || "").toString().replace(/\|/g, " ");
              const ev     = (r.event || "").toString();
              const upd    = (r.updated_at || "").toString();
              const url    = (r.html_url || "").toString();
              lines.push(`| ${status} | ${wf} | ${ev} | ${upd} | ${url} |`);
            }

            core.summary.addRaw(lines.join("\n")).write();

      - name: Artifacts hint
        if: always()
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Notes" >> $GITHUB_STEP_SUMMARY
          echo "- For agentic outputs, open the run -> **Artifacts** (AgentOutput / agent-output)." >> $GITHUB_STEP_SUMMARY